name: Site notifier

on:
    schedule:
        - cron: "*/15 * * * *"
    workflow_dispatch:

jobs:
    notify:
        name: Update News
        runs-on: ubuntu-latest
        permissions:
            issues: write

        steps:
            - uses: actions/checkout@v4

            - name: Restore state cache
              uses: actions/cache@v4
              with:
                  path: state.json
                  key: notifier-state-main
                  restore-keys: |
                      notifier-state-main

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Install dependencies
              run: uv sync

            - name: Update News
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  FORCE_RECHECK: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
              run: source .venv/bin/activate && python sites.py
